name: riverpod_playground
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  hooks_riverpod: ^2.2.1
  flutter_lints: ^3.0.0

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_riverpod: ^2.5.1

  # Optional: for generating Riverpod providers (improves code generation)
  build_runner: ^2.3.2
  riverpod_generator: ^2.4.2
riverpod_lint: ^2.3.12


flutter:
  uses-material-design: true
